### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by eguneys** [arikwex/infernal-sigil#3]
I am sorry, I already used your audio.js file as is in my this year's entry, the repo is here: https://github.com/eguneys/blue-retro2023.

Since the same file is already available under MIT on your previous entry I thought it would be ok. I already added one of your music from this repository, I guess that would be ok, I also added you to my game's credits. Feel free to play along, it's under development.

**Comment by arikwex** [comment]
added license now -- you good.
